version: '3'
networks:
  cluster_subnet:
    name: cluster_subnet
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.1.0/24
          gateway: 172.16.1.1

services:
  opensearch-node1:
    image: opensearchproject/opensearch:2.9.0
    container_name: opensearch-node1
    networks:
      cluster_subnet:
        ipv4_address: 172.16.1.2
    environment:
      &environment
      cluster.name: source-cluster
      node.name: opensearch-node1
      bootstrap.memory_lock: "true"
      OPENSEARCH_JAVA_OPTS: "-Xms512m -Xmx512m"
      discovery.type: single-node
      plugins.security.disabled: "true"
      reindex.remote.allowlist: 172.16.1.2:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - type: volume
        target: /usr/share/opensearch/data

  opensearch-node2:
    image: opensearchproject/opensearch:2.9.0
    container_name: opensearch-node2
    networks:
      cluster_subnet:
        ipv4_address: 172.16.1.3
    environment:
      <<: *environment
      cluster.name: target-cluster
      node.name: opensearch-node2
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - type: volume
        target: /usr/share/opensearch/data

  shotover:
    depends_on:
      - opensearch-node1
    image: conorbros/shotover
    network_mode: host
    ports:
      - 9200:9200
    volumes:
      - type: bind
        source: $PWD
        target: /config
